### ISSUE TITLE
Trained model for testing purpose

### ISSUE THREAD

**Issue by amit2319** [trushkin-ilya/face-anti-spoofer#28]
Hi Author,

Any Chance you guys are releasing trained-model as well.

Or the CASIA-SURF dataset itself. ?

**Comment by trushkin-ilya** [comment]
Hi Amit,
Thank you for opening this issue.
Right now I am preparing models for Google Drive upload, so they will be available for download soon.This change will be added to #27.

**Comment by grib0ed0v** [comment]
@amit2319 thanks for the interest to the repo. 

As @trushkin-ilya already said, model weights to be published very soon.

For the dataset sharing, since it is not public and you need to request access to it, we can't publish it. Please read more info [here](https://competitions.codalab.org/competitions/22151).
